name: Deploy

on:
  push:
    branches:
      - main

env: 
  SHORT_SECRET_KEY: ${{ secrets.SHORT_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}